# This file was generated by GoReleaser. DO NOT EDIT.
cask "crypt" do
  version "0.0.0-edge"

  on_macos do
    on_intel do
      sha256 "d9fc736635ead1868bd6f6b076203decb45fcc71b4aadb5eca867a2c347e1598"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "15190924b9c7da1366238f382574eda88594d22213745f070941e792d3cc2320"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_arm64.tar.gz"
    end
  end

  name "crypt"
  desc "Run coding agents inside disposable Anka macOS VMs"
  homepage "https://github.com/veertuinc/crypt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crypt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/crypt"]
    end
  end

  # No zap stanza required

end
