# This file was generated by GoReleaser. DO NOT EDIT.
cask "crypt" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "e7b21e54e66422683dd6dc60eb84ea18dc2620cebdc48fd5fcaa25823f702c2b"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c94ed9c108da3520a0ab876bbfbc64f21bf0aac4dcd7f03c6647b2c6c63bd5e9"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_arm64.tar.gz"
    end
  end

  name "crypt"
  desc "Run coding agents inside disposable Anka macOS VMs"
  homepage "https://github.com/veertuinc/crypt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crypt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/crypt"]
    end
  end

  # No zap stanza required

end
