# This file was generated by GoReleaser. DO NOT EDIT.
cask "crypt" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "6ce20f2f0e8b8b8fdc451a6545ebe1a1eebd3a0a91c33ff028c2ca08956ae8d6"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9fe9b52fd053592d3dcf864bb87acaf775c932c67bcf875bbace0364a75fe737"
      url "https://github.com/veertuinc/crypt/releases/download/v#{version}/crypt_darwin_arm64.tar.gz"
    end
  end

  name "crypt"
  desc "Run coding agents inside disposable Anka macOS VMs"
  homepage "https://github.com/veertuinc/crypt"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "crypt"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/crypt"]
    end
  end

  # No zap stanza required

end
